language: rust
cache: cargo

addons:
  apt:
    packages:
      - libfontconfig1-dev

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --all-features

matrix:
  allow_failures:
    - rust: nightly
