language: rust
cache: cargo
dist: xenial

addons:
  apt:
    packages:
      - libfontconfig1-dev
      - libxkbcommon-dev
      - libxcb-keysyms1-dev

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --all-features

matrix:
  allow_failures:
    - rust: nightly
