[package]
name = "wmfocus"
version = "0.1.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]

[features]
i3 = ["i3ipc"]

[dependencies]
clap = "2.31"
i3ipc = { version = "0.8", optional = true }
fps_clock = "2.0"
font-loader = "0.7"
itertools = "0.7"
rusttype = "0.7"
glutin = "0.18"
gfx = "0.17"
gfx_glyph = "0.12"
gfx_window_glutin = "0.26"
gfx_device_gl = "0.15"

[profile.release]
lto = true
