[package]
name = "wmfocus"
version = "0.1.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]

[features]
i3 = ["i3ipc"]

[dependencies]
clap = "2.31"
glium = "0.21"
glium_text_rusttype = "0.3"
i3ipc = { version = "0.8", optional = true }
fps_clock = "2.0"
font-loader = "0.7"
cgmath = "0.16"

[patch.crates-io]
glium = { git = 'https://github.com/senet4er/glium'}
glium_text_rusttype = { git = 'https://github.com/svenstaro/glium_text_rusttype.git', branch = "patch-1"}
