[package]
name = "wmfocus"
version = "0.1.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]

[features]
i3 = ["i3ipc"]

[dependencies]
clap = "2.31"
glium = "0.21"

i3ipc = { version = "0.8", optional = true }

[patch.crates-io]
glium = { git = 'https://github.com/senet4er/glium'}
