[package]
name = "wmfocus"
version = "1.0.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]

[features]
i3 = ["i3ipc"]

[dependencies]
cairo-sys-rs = "0.7"
clap = "2.31"
css-color-parser = "0.1"
font-loader = "0.7"
i3ipc = { version = "0.8", optional = true }
itertools = "0.7"
log = "0.4"
pretty_env_logger = "0.2"
xcb = "0.8"
xkbcommon = "0.2"

[dependencies.cairo-rs]
version = "0.5.0"
features = ["xcb"]

[dependencies.xcb-util]
version = "0.2"
features = ["keysyms"]

[dependencies.x11]
version = "2.18.1"
features = ["xlib"]

[profile.release]
lto = true
